### DISCUSSION TITLE
Cloudflare Workers, Service Bindings and RPC

### DISCUSSION THREAD

**Discussion by boojum** [honojs/hono#2486] [Q&A]
I'm following the [docs](https://hono.dev/guides/rpc) trying to get two CF Workers to comunicate via RPC, using `hono@4.2.2`. Unfortunatelly, I can't get it to work and only receive `Error No Response!`. If someone could point out what I'm doing wrong I would be grateful!

worker-a
```toml
name = "worker-a"
compatibility_date = "2023-12-01"

[dev]
port = 3001
```
```ts
import { Hono } from 'hono'
import { zValidator } from '@hono/zod-validator'
import { z } from 'zod'

const app = new Hono()

const route = app.get(
  '/api/hello',
  zValidator(
    'query',
    z.object({
      name: z.string(),
    }),
  ),
  (c) => {
    const { name } = c.req.valid('query')
    return c.json({
      message: `Hello! ${name}`,
    })
  },
)

export type AppType = typeof route

export default app
```

worker-b
```toml
name = "tokens"
compatibility_date = "2023-12-01"

services = [
  { binding = "hello", service = "worker-a" }
]

[dev]
port = 3002
```
```ts
import { Hono } from 'hono'
import { AppType } from '../worker-a/src/index'
import { hc } from 'hono/client'
import { Fetcher } from '@cloudflare/workers-types'

type Bindings = {
  hello: Fetcher
}

const app = new Hono<{ Bindings: Bindings }>()

app.get('/', async (c) => {
  const client = hc<AppType>('http://localhost:3001/', {
    fetch: c.env.hello.fetch.bind(c.env.hello),
  })

  const res = await client.api.hello.$get({
    query: {
      name: 'Hono',
    },
  })

  const data = await res.json()

  return c.json(data.message)
})
```
