### ISSUE TITLE
Deploy Hono app in GitHub Action 

### ISSUE THREAD

**Issue by metrue** [honojs/hono#185]
Since hono is using wrangler@beta, so we can not use the official action [wrangler-action](https://github.com/cloudflare/wrangler-action) since it is still in version 1.x.x.

And I tried with script, 
```yml
name: workers

on:
  push:
    branches:
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.7.0
      - name: publish
        run: |
          cd api;
          npx wrangler@beta publish index.js;
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
```

It complains with error log,
```
cd api;
  npx wrangler@beta publish index.js;
  shell: /usr/bin/bash -e {0}
  env:
    CF_API_TOKEN: ***
npm WARN exec The following package was not found and will be installed: wrangler@beta
Using "CF_API_TOKEN" environment variable. This is deprecated. Please use "CLOUDFLARE_API_TOKEN", instead.
 ⛅️ wrangler 0.0.2[7](https://github.com/gikiapp/giki.api/runs/6211614457?check_suite_focus=true#step:4:7) 
--------------------
No account id found, quitting...

If you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/issues/new.
Error: Process completed with exit code 1.
```

Any idea to solve this?
