### ISSUE TITLE
serveStatic not working (ReferenceError: __STATIC_CONTENT_MANIFEST is not defined)

### ISSUE THREAD

**Issue by ArnabXD** [honojs/hono#247]
### Info

- hono : 1.3.3
- wrangler : v2

### Wrangler configuration - 

```toml
name = "test"
main = "src/index.ts"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "ARNAB", preview_id = "", id="" }
]

[site]
bucket =  "./public"
```

### Code - 

```ts
import { Hono } from "hono";
import { serveStatic } from "hono/serve-static";
import { renderSSR } from "nano-jsx";
import Home from "./pages/Home";

const app = new Hono();

app.use("/img/*", serveStatic({ root: "./" }));
app.get("/", async (ctx) => ctx.html(renderSSR(Home)));

export default app;
```

### Assets : 

```
./public
└── img
    ├── cf.png
```

# Error : 

`GET /img/cf.png`  crashes with an internal server error.

```
8:46:17 AM GET /img/cf.png 500
ReferenceError: __STATIC_CONTENT_MANIFEST is not defined             
[1]     at getContentFromKVAsset (index.js:718:9)
[1]     at index.js:869:70
[1]     at dispatch (index.js:301:34)
[1]     at index.js:286:16
[1]     at Hono2.dispatch (index.js:660:27)
```
