### ISSUE TITLE
env vars with miniflare

### ISSUE THREAD

**Issue by waptik** [honojs/hono#270]
Hi. I need help making hono's environment variables work with miniflare.
 Here is a snippet of my code :

**wrnagler.toml**
```toml
...
[[rules]]
type = "ESModule"
globs = ["**/*.ts"]

[build]
command = "yarn build"

[vars]
# The `cache-control` header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control. Optional, the `cache-control` header is omitted if unset.
CACHE_CONTROL = "max-age=86400"
API_URL = "***https://api.paystack.co***"
ENABLE_AUTH_CHECKER = false

[env.production.vars]
ENABLE_AUTH_CHECKER = true

[miniflare]
live_reload = true
watch = true
# https = true
...
```

**package.json**
```json
...
 "scripts": {
    "build": "esbuild --bundle --sourcemap --minify --outdir=dist ./src/index.ts",
    "test": "jest --verbose",
    "validate": "jest ./validation/* --verbose",
    "dev": "miniflare",
    "deploy": "wrangler publish src/index.ts",
    "mf": "miniflare"
  },
...
```

Typescript code
```ts
// src/types.ts
export interface Env {
  ENABLE_AUTH_CHECKER: boolean;
  API_URL: string;
  CACHE_CONTROL: string;
  API_KEY: string;
  SECRET_KEY: string;
}

// src/index.ts
...
import {Env} from "./types";

export const app = new Hono<Env>();
...

// auth middleware
app.use("/api/*", async (ctx, next) => {
  console.log("vars", { env: ctx.env });

  if (ctx.env.ENABLE_AUTH_CHECKER) {
    // code inspired by https://github.com/cloudflare/templates/blob/0f62f56ba31389def65343c99d091222d4e7a0af/worker-worktop/src/utils/token.ts#L18
    const auth = ctx.req.headers.get("Authorization");
    if (!auth) {
      ctx.text('Missing "Authorization" header', 401);
      return;
    }

    const [scheme, key] = auth.split(/\s+/g);
    if (!scheme || !key) {
      ctx.text('Invalid "Authorization" header', 400);
      return;
    }

    if (ctx.env.API_KEY !== key) {
      ctx.text('Invalid "Authorization" token', 401);
      return;
    }
  }

  await next();
});
```

Now when I run `yarn dev` and goto `http://localhost:8787/api/some/path`,  get the following errors:
```sh
 --> GET /api/some/path 500 6ms
GET /api/some/path 500 Internal Server Error (12.81ms)
  <-- GET /api/some/path
vars { env: undefined }
TypeError: Cannot read properties of undefined (reading 'ENABLE_AUTH_CHECKER')
```
