### ISSUE TITLE
Clarification on KV usage

### ISSUE THREAD

**Issue by byt3bl33d3r** [honojs/hono#340]
Heya, i'm getting the following error when trying to use KV in Cloudflare workers. I took a look at the [example blog project](https://github.com/honojs/examples/tree/f056eb1838339f339118f31700d0d5f977df244b/blog) which uses them. Seems like the below should be working?

```typescript
export const auth = new Hono()
auth.get('/login', async(c) => {
    await c.env.OAUTH_STATES.put(state, code_verifier, {expirationTtl: 600})
}
```

However, i get the following error:
```
TypeError: Cannot read properties of undefined (reading 'OAUTH_STATES')
```

My `wrangler.toml`:

```toml
name = "api-dev"
main = "src/index.ts"
compatibility_date = "2022-06-25"
workers_dev = true
node_compat = true
kv_namespaces = [
    { binding = "OAUTH_STATES", preview_id = "<ID>", id = "<ID>" }
]

vars = { ENVIRONMENT = "dev" }

[env.production]
name = "api"
vars = { ENVIRONMENT = "production" }

[env.staging]
name = "api-staging"
vars = { ENVIRONMENT = "staging" }
```

Cheers!
