### ISSUE TITLE
ci: automatically close issues marked as “not bug” over time

### ISSUE THREAD

**Issue by EdamAme-x** [honojs/hono#3607]
https://github.com/honojs/hono/issues/751#issuecomment-2182128433

## Propose workflow
If an issue labeled `not bug` is inactive for 7 days, it will be labeled `stale` and start the time limit of the closing issue.  
A warning will be given that the issue will be closed. If there is no activity for two days, it will be closed.

```yaml
name: Close stale issues with "not bug" label

on:
  schedule:
    - cron: '0 0 * * *' 

permissions:
  contents: write
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues with "not bug" label
        uses: actions/stale@v8
        with:
          days-before-stale: 7                    
          days-before-close: 2                     
          stale-issue-message: 'This issue has been marked as stale due to inactivity.'
          close-issue-message: 'Closing this issue due to inactivity.'
          exempt-issue-labels: ''                  
          only-labels: 'not bug'                   
          operations-per-run: 30                   
          remove-stale-when-updated: true          
```
